export const SRI_LANKA_DISTRICTS = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Monaragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya",
];

export const OFFER_CATEGORIES = [
  "Electronics",
  "Fashion & Clothing",
  "Food & Beverage",
  "Health & Beauty",
  "Home & Living",
  "Travel & Tourism",
  "Education",
  "Entertainment",
  "Automotive",
  "Services",
  "Groceries",
  "Gifts & Hobbies",
];
